package sf.net.experimaestro.manager;

import java.util.Map;

import javax.xml.namespace.QName;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import org.w3c.dom.Document;
import org.w3c.dom.DocumentFragment;
import org.w3c.dom.Node;

import sf.net.experimaestro.utils.log.Logger;

public abstract class Task {
	public final static DocumentBuilderFactory dbFactory = DocumentBuilderFactory
			.newInstance();
	final static private Logger LOGGER = Logger.getLogger();

	/**
	 * The information related to this class of experiment
	 */
	protected TaskFactory factory;

	protected Task(TaskFactory information) {
		this.factory = information;
	}

	/**
	 * Set a parameter.
	 * 
	 * Utility function that wraps the string into an XML fragment
	 * 
	 * @param id
	 * @param value
	 */
	public void setParameter(DotName id, String value) {
		try {
			DocumentBuilder docBuilder = dbFactory.newDocumentBuilder();
			DocumentFragment fragment = docBuilder.newDocument()
					.createDocumentFragment();
			fragment.setTextContent(value);
			setParameter(id, fragment);
			LOGGER.debug("Set string parameter [%s]: %s", id,
					fragment.getTextContent());
		} catch (ParserConfigurationException e) {
			throw new RuntimeException(e);
		}
	}

	/**
	 * Returns the factory that created this task
	 */
	public TaskFactory getFactory() {
		return factory;
	}

	/**
	 * Get the list of sub tasks
	 * 
	 * @return A map or null
	 */
	public Map<String, Task> getSubTasks() {
		return null;
	}

	/**
	 * Set a parameter
	 * 
	 * @param id
	 *            The identifier for this parameter (dot names)
	 * @param value
	 *            The value to be set (this should be an XML fragment)
	 */
	abstract public void setParameter(DotName id, Node value);

	/**
	 * Get the list of parameters
	 */
	abstract public Map<DotName, NamedParameter> getParameters();

	/**
	 * Get the current outputs (given the current parameters)
	 */
	abstract public Map<DotName, QName> getOutputs();

	/**
	 * Run this task. The output is a valid XML document where top level
	 * elements correspond to the different outputs generated by the method
	 * 
	 * @return An XML description of the output
	 */
	public abstract Document run();

}
