#!/usr/bin/python

import os.path
import sys
import subprocess

# --- Set some variables

dir=os.path.dirname(os.path.abspath(__file__))
version="0.0.1-SNAPSHOT"
jarname="experimaestro-%s.jar" % version

# --- Check paths

def jarpaths():
    yield os.path.join(dir, jarname)
    yield os.path.join(os.path.dirname(dir), "target", "experimaestro-%s-bin" % version, jarname)

jarpath = None
for f in jarpaths():
    print "Trying %s" % f
    if os.path.isfile(f):
        jarpath = f
        break

if jarpath is None: raise Exception("Could not find experimaestro jar file")

# --- Run command

command = sys.argv.pop(0)

if command == "server":
    subprocess.call(["java","-Xmx1g","-jar",jarpath] + sys.argv[1:])
else:
    raise Exception("Unknown command %s", command)
